### ISSUE TITLE
Bestellübersicht / finale Seite

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/spacemuffin#10]
Als Redakteurin möchte ich - vor der Auftragsvergabe - einen Überblick über meine Bestellung bekommen und sehen, was sie kostet. 
Als Verlag oder als tactilenews möchte ich das Preisschild abschalten können, die Bestellübersicht aber beibehalten.

**Comment by drjakob** [comment]
![8510384b-6fb3-4ffe-95b3-af8a24fd000d](https://user-images.githubusercontent.com/11591426/48082212-3efe7980-e1f2-11e8-960f-5a80eaf7ee30.jpeg)
