### ISSUE TITLE
Startseite Neues Manuskript erfassen

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/spacemuffin#11]
Als Redakteurin möchte ich auf einer Startseite den Namen meines Beitrags (das Beitragsformat) und den Ausspielkanal (die Figur) festlegen können. (Später auch das Format.)

Begriffe fürs Dev in English:
Nachricht = news
Reportage = report
Interview = interview
Frage und Antwort = q&a
Satire = standup
Gutenachtgeschichte = latenight

**Comment by drjakob** [comment]
![b67cd8c8-448c-4f75-b4e6-86bac80c8f9d](https://user-images.githubusercontent.com/11591426/48082616-5d18a980-e1f3-11e8-96d7-6525bac1adca.jpeg)

**Comment by appinteractive** [comment]
@drjakob @FrauCsu welche Typen (Reportage, etc...) und welche Figuren (Ralph, Bär, etc...) sollen aufgelistet werden?

**Comment by drjakob** [comment]
Formate: Reportage/Stand-Up/Q&A/Protokoll/Buchtipp/Interview
Figuren:  Eisbär / Ralph / Krake / Newspirat

**Comment by drjakob** [comment]
![86e5f98f-551a-44ae-bde8-d6594017df4a](https://user-images.githubusercontent.com/11591426/48126765-5422e900-e282-11e8-8d57-99ecb92c3476.jpeg)

**Comment by tillprochaska** [comment]
@FrauCsu & @drjakob: Die Sprachstile in den verschiedenen Screens sind gerade nicht vereinbar. 

Empty State: »Du hast noch keine Beiträge«
Start Screen: »Ich möchte eine Reportage…«

**Comment by tillprochaska** [comment]
Notiz an mich: Hauptsprecherauswshl hier, weil im 2. Schritt schon zusätzliche Stimmen
