### ISSUE TITLE
Button »Produzieren« speichert eingegebene Daten

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/spacemuffin#12]
Als Redakteurin möchte ich  auf der Go-Übersichtsseite final auf einen Button klicken, um meinen Auftrag abzuschicken.

**Comment by drjakob** [comment]
![51e9478a-d148-4651-8700-9bde1e2e8db7](https://user-images.githubusercontent.com/11591426/48082335-a87e8800-e1f2-11e8-997b-2650bfa29ae2.jpeg)

**Comment by appinteractive** [comment]
Für den Anfang würde ich vorschlagen die Daten mit ID in die Local Storage zu speichern.

**Comment by drjakob** [comment]
Dafür

-- 
Dr. Jakob J. E. Vicari
freier Wissenschaftsredakteur
post@jakobvicari.de
+49 (0)4131 799 85 61

Wissenschaftsjournalist des Jahres 2015, Medium Magazin
Sieger Formatfestival 2015, Medieninnovationszentrum Babelsberg
Nominiert Nannen-Preis 2016, Web-Reportage

**Comment by appinteractive** [comment]
@roschaefer done?
