### ISSUE TITLE
Button: Zur Bestellübersicht

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/spacemuffin#13]
Als Redakteuerin möchte ich den Editor verlassen, in dem ich auf einen Button klicke, der mich zu einer Bestellübersicht weiter leitet.

**Comment by drjakob** [comment]
![38dcf677-b693-470e-a3f8-2d7fe27391c2](https://user-images.githubusercontent.com/11591426/48082504-1d51c200-e1f3-11e8-93ae-e3c5cfe1a02e.jpeg)
