### ISSUE TITLE
Preis berechnen

### ISSUE THREAD

**Issue by FranciNowak** [tactilenews/spacemuffin#14]
Als Redakteurin und auch als Verlag möchte ich wissen, wie viel mich das Produkt kosten wird, damit ich kalkulieren kann.

**Comment by drjakob** [comment]
![bff0b925-5ae3-49ed-b82b-34e15ae742de](https://user-images.githubusercontent.com/11591426/48082433-e4b1e880-e1f2-11e8-9df2-54d64b4c0dfa.jpeg)

**Comment by TheAmazingPT** [comment]
#22
