### ISSUE TITLE
BUG Preisetikett

### ISSUE THREAD

**Issue by drjakob** [tactilenews/spacemuffin#50]
Das Preisetikett auf der "Fast Geschafft"-Seite wird 50€ TEURER, wenn ich ein datum 5 Tage in der Zukunft wähle. Es soll aber BILLIGER werden.

**Comment by TheAmazingPT** [comment]
Kann geclosed werden oder?

**Comment by drjakob** [comment]
Ja

-- 
Dr. Jakob J. E. Vicari
freier Wissenschaftsredakteur
post@jakobvicari.de
+49 (0)4131 799 85 61

Wissenschaftsjournalist des Jahres 2015, Medium Magazin
Sieger Formatfestival 2015, Medieninnovationszentrum Babelsberg
Nominiert Nannen-Preis 2016, Web-Reportage
