### ISSUE TITLE
Microcopy

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/spacemuffin#54]
Für alle Buttons, die man nicht versteht, möchte Robert gerne Erklärtexte. Astrid schreibt die.

**Comment by drjakob** [comment]
EMPTY STATE Dashboard

CREAtE

EDITOR

REVIEW


Unter den Datepicker:
 "Wir senden Dir den fertigen Beitrag per E-Mail."

Preis: Nur runde Eurobeträge

**Comment by tillprochaska** [comment]
> Du hast fünf Beiträge .

Es wird max. 1 Beitrag im System sein, den zeigen wir aber natürlich in einer Tabellenzeile anzeigen.

**Comment by tillprochaska** [comment]
@FrauCsu @drjakob: Ich hätte gerne noch Texte für

* Button »Loslegen« in CREATE, der erklärt, das auf der nächsten Seite der eigentliche Beitrag eingefügt werden kann
* Platzhalter im Editor (momentan »Füge hier deinen Beitrag ein«)
* Text über Editor oder neben Editor, der erklärt, dass Red. Text highlighten oder Cursor an bestimmte Stelle setzen kann
* Button »Auftrag überprüfen« in EDITOR, der erklärt, dass auf der nächsten Seite Lieferzeit etc. ausgewählt werden können und noch einmal alle Details angezeigt werden können

**Comment by drjakob** [comment]
- Loslegen: "Hier kannst Du Dein Manuskript in wenigen Minuten zum Vertonen vorbereiten."
- Platzhalter im Editor: "Füge hier dein Manuskript per Copy&Paste ein. Dann kannst Du es mit Geräuschen und Originaltönen ausstatten."
– Button "Auftrag überprüfen": "Auf der nächsten Seite siehs Du deinen Auftrag in der Übersicht und kannst die Produktion beauftragen."

**Comment by drjakob** [comment]
Text über Editor: "Du kannst Geräusche als Athmo hinter Text legen, indem du Textstellen markierst {MARKERSYMBOL). Oder als Sound-Effekt zwischen zwei Wörter einfügen (PIN-Symbol), indem du den Cursor an die passende Stelle setzt.

**Comment by appinteractive** [comment]
> Platzhalter im Editor: "Füge hier dein Manuskript per Copy&Paste ein. Dann kannst Du es mit Geräuschen und Originaltönen ausstatten." 
erledigt
