### ISSUE TITLE
Längenangabe Wie lange ist mein Text gesprochen?

### ISSUE THREAD

**Issue by FranciNowak** [tactilenews/spacemuffin#7]
Als Redakteurin möchte ich wissen, wie lang mein Audioprodukt wird, um eine Sendung aus mehreren Audioprodukten planen zu können und/oder den Eltern eine verlässliche Zeitorientierung geben zu können.

**Comment by drjakob** [comment]
![187128ad-df1a-45a7-9cde-3c0de952de12](https://user-images.githubusercontent.com/11591426/48082898-0790cc80-e1f4-11e8-9e2d-90080c85323d.jpeg)
