### ISSUE TITLE
to be done: Dashboard Site / Overview

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/spacemuffin#77]
Still missing: Site to Start Using Space Muffin after first draft has been saved. It needs three buttons / lists for 

- Your drafts
- In Production
- Your Archive

<img width="879" alt="bildschirmfoto 2018-11-09 um 19 40 09" src="https://user-images.githubusercontent.com/44811680/48282382-d3b6e080-e459-11e8-841c-ba7acc732323.png">

**Comment by tillprochaska** [comment]
Momentan gibt es ja schlicht keine Möglichkeit, mehrere Beiträge zu erstellen. Auch gibt es keine Möglichkeit, einen Beitrag zu archivieren. D. h. in der Folge, dass der Beitrag, der hier angezeigt wird, immer ein beauftragter Beitrag ist.

Es gibt jetzt zwei Möglichkeiten:

* Wir ergänzen einfach ein »Beauftragte Beiträge« über dem Eintrag oder einen Hinweis wie in #91 erwähnt.
* Wir setzen tatsächlich um, dass Nutzer mehrere Beiträge erstellen können.

**Comment by drjakob** [comment]
Wir belassen es erstmal wie in #91.

**Comment by tillprochaska** [comment]
Schließe ich für #91
