### ISSUE TITLE
Move SendGrid Proxy logic from GCF to nuxt

### ISSUE THREAD

**Issue by TheAmazingPT** [tactilenews/spacemuffin#79]
https://github.com/TheAmazingPT/gcf-sendgrid-proxy

**Comment by appinteractive** [comment]
Here is an Module (nuxt-axios)[https://axios.nuxtjs.org/] which is used for Ajax requests that you can configure to proxy requests through the node backend.

**Comment by FrauCsu** [comment]
Haben wir keine Ahnung von. @tillprochaska ?

**Comment by TheAmazingPT** [comment]
You could also simply deploy the app on Firebase (https://firebase.google.com) and use the Firebase Cloud Functions for the proxy. This hosting offers many other features aswell, which might be useful for the project =)

**Comment by tillprochaska** [comment]
Ich sehe mir das noch genauer an, würde es aber bevorzugen, die Mail-API nicht separat zu deployen, sondern direkt in der Anwendung zu halten.
