### ISSUE TITLE
Review: Autor fehlt

### ISSUE THREAD

**Issue by drjakob** [tactilenews/spacemuffin#89]
Auf der review-Seite steht "Autor", da müsste der Name des Autoren erscheinen.

**Comment by tillprochaska** [comment]
Notiz an mich selbst: <img width="458" alt="screenshot 2019-01-03 08 03 28" src="https://user-images.githubusercontent.com/1512805/50626367-11058f00-0f2e-11e9-9a4c-703e0edfc0ee.png">

**Comment by drjakob** [comment]
ich denke, das ist klar: Statt "Autor" soll der erfasste Name eingesetzt werden.

**Comment by tillprochaska** [comment]
Jetzt weiß ich auch, warum daran gedacht hat, den Autor anzuzeigen: Wir erfassen den Autor im gesamten Prozess überhaupt nicht. Vorschlag: Die zwei Wörter »von Autor« einfach komplett streichen.

**Comment by drjakob** [comment]
Guter Punkt. Gute Lösung.
