### ISSUE TITLE
Atmoauswahl

### ISSUE THREAD

**Issue by FranciNowak** [tactilenews/spacemuffin#9]
Als Redaktuerin möchte ich den Text eines Autors mit den passenden Geräuschen unterlegen, um das Audioprodukt ansprechender zu gestalten.

**Comment by drjakob** [comment]
![b2463626-06b2-42ff-8340-a10acffe2468](https://user-images.githubusercontent.com/11591426/48082747-aa951680-e1f3-11e8-9444-de067b2ed68a.jpeg)
