### ISSUE TITLE
Success-Seite: Autor und Tage werden nicht angezeigt

### ISSUE THREAD

**Issue by drjakob** [tactilenews/spacemuffin#90]
Success-Seite: Autor und Tageszahl wird nicht richtig angezeigt

**Comment by tillprochaska** [comment]
<img width="975" alt="screenshot 2019-01-03 07 58 39" src="https://user-images.githubusercontent.com/1512805/50626243-64c3a880-0f2d-11e9-9da9-1915915596e4.png">
