### ISSUE TITLE
Dashboard: zerschossen, sobald ein Beitrag angelegt

### ISSUE THREAD

**Issue by drjakob** [tactilenews/spacemuffin#91]
Wenn ich fertig mit dem ersten Beitrag bin und auf den Bitton "Zum Dashboard" auf der Success-Seite klicke, komme ich auf ein zerschossenes Dashboard.

**Comment by tillprochaska** [comment]
Kannst du das erläutern? Ich sehe das hier:

<img width="981" alt="screenshot 2019-01-03 07 55 09" src="https://user-images.githubusercontent.com/1512805/50626149-e6ff9d00-0f2c-11e9-87ef-2c7b827d965b.png">

Wenn ich es richtig in Erinnerung habe, ist das genau das, was angezeigt werden soll. Ich sehe aber auch, dass die Darstellung vielleicht nicht ausreichend Informationen bereitstellet. Evtl. sollten wir zusätzlich Informationen zum Status des Beitrags anzeigen, also z. B. einen Text »Du hast diesen Beitrag beauftragt und kannst ihn deshalb nicht mehr ändern. Wir produzieren deinen Beitrag bis zum {{DATUM}}.«
